### ISSUE TITLE
Clicking outside the modal allows user to tab between non-dialog elements

### ISSUE THREAD

**Issue by lukito** [gdkraus/accessible-modal-dialog#4]
Referring to http://accessibility.oit.ncsu.edu/training/aria/modal-window/version-3/

1. Click "view the modal window" to show the modal dialog.
2. Click anywhere outside the modal, in the "greyed-out" area.
3. Hit "tab" and you can see the focus move between the links and buttons of the main content.

**Comment by lectrotext** [comment]
I'd suggest preventing the loss of focus from the modal with js.  While the aria-hidden=true attribute prevents speaking of links, it doesn't meets the criteria for a modal which must keep focus until submitted or canceled.

**Comment by gdkraus** [comment]
This is fixed now in version 4
